---
title: "Belajar Visualisasi"
output: html_notebook
---



# Exercise 1

# Run ggplot(data = mpg). What do you see?

```{r}
ggplot(data=mpg)
```

# How many rows are in mpg? How many columns?
```{r}
dim(mpg)
```



# What does the drv variable describe? Read the help for ?mpg to find out.
```{r}
?mpg
```


# Make a scatterplot of hwy vs cyl.
```{r}
ggplot(data=mpg) + geom_point(mapping = aes(x = hwy, y = cyl))
```



# What happens if you make a scatterplot of class vs drv? Why is the plot not useful?
```{r}
ggplot(data=mpg) + geom_point(mapping = aes(x = class, y = drv))
```

# mengganti color = class

```{r}
ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy, color =class))
```


# mengganti alpha = class

```{r}
ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy, alpha =class))
```

# mengganti alpha = color 



```{r}
ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy),color ='blue')
```



#statistic
```{r}

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(.~ class, nrow=2) 
```



# Coordinates
```{r}
ggplot(data = mpg) +
geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(.~ class, nrow = 1) +
  stat_smooth(aes(x=displ, y=hwy), method = 'lm', se = F, col="red") +
  scale_y_continuous("Displacement of Engines in litres") +
  scale_x_continuous("Highway miles per gallon") + coord_cartesian()

```


# Themes

```{r}

ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_wrap(.~ class, nrow = 1) +
  stat_smooth(aes(x=displ, y=hwy), method = 'lm', se = F, col="red") +
  scale_y_continuous("Displacement of Engines in litres") +
  scale_x_continuous("Highway miles per gallon")  + coord_cartesian() +
  theme(panel.background = element_blank())
```












